import pumpz as pz

f_aq = open("aq.ppl", "w")
f_org = open("org.ppl", "w")
# f_wash = open("wash.ppl", "w")
f_dummy = open("dummy.ppl", "w")
f_master = open("master.ppl", "w")

aq = pz.Pump(f_aq, 26.59)
org = pz.Pump(f_org, 26.59)
dummy = pz.Pump(f_dummy, 26.59)
# wash = pz.pump(f_wash, 26.59)
master = pz.masterppl(f_master)
master.quickset({0: org, 1: aq})

pz.Pump.init(aq, org, dummy)
aq.rate(22, 20, "wdr")
org.rate(22, 20, "wdr")
# wash.rat(21,50,'wdr')
aq.rate(10, 20, "inf")
# aq.pause(5 * 60)
print(aq.time)
print(org.time)
pz.Pump.sync(aq, org, dummy)
print(aq.time)
print(org.time)
org.rate(10, 20, "inf")
org.pause(60)
pz.Pump.sync(aq,org)
aq.rate(22,50,'wdr')
org.rate(22,50,'wdr')
dummy.pause(5*60)
pz.Pump.sync(aq,org,dummy)
aq.loopstart(2)
org.loopstart(2)
aq.rate(22,50,'inf')
org.rate(22,50,'inf')
aq.rate(22,50,'wdr')
org.rate(22,50,'wdr')
aq.loopend()
org.loopend()
aq.rate(22,50,'inf')
org.rate(22,50,'inf')

# pz.Pump.sync(org,wash)
# wash.loopstart(2)
# wash.rate(21, 50, "inf")
# wash.rate(21, 50, "wdr")
# wash.loopend()
# wash.rate(21, 50, "inf")
pz.Pump.stop(aq, org)
