import pumpz as pz

f_aq = open("aq.ppl", "w")
f_org = open("org.ppl", "w")
f_wash = open("wash.ppl", "w")
f_master = open('master.ppl','w')

aq = pz.pump(f_aq, 26.59)
org = pz.pump(f_org, 26.59)
wash = pz.pump(f_wash, 26.59)

master = pz.masterppl(f_master)
master.quickset({0:org,1:aq,2:wash})

pz.pump.init(aq,wash,org)
aq.rat(22, 20, "wdr") 
org.rat(22, 20, "wdr") 
wash.rat(21,50,'wdr')
aq.rat(10, 20, "inf") 
aq.pas(5 * 60)
pz.pump.sync(aq, org)
org.rat(10, 20, "inf") 
org.pas(5 * 60)
pz.pump.sync(org,wash)
wash.loopstart(2)
wash.rat(21, 50, "inf")
wash.rat(21, 50, "wdr")
wash.loopend()
wash.rat(21, 50, "inf")
pz.pump.stop(aq,org,wash)